/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/feedbacks": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.feedbacks.id"];
          form_id?: parameters["rowFilter.feedbacks.form_id"];
          type?: parameters["rowFilter.feedbacks.type"];
          feedback?: parameters["rowFilter.feedbacks.feedback"];
          name?: parameters["rowFilter.feedbacks.name"];
          url?: parameters["rowFilter.feedbacks.url"];
          is_public?: parameters["rowFilter.feedbacks.is_public"];
          created_at?: parameters["rowFilter.feedbacks.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["feedbacks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** feedbacks */
          feedbacks?: definitions["feedbacks"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.feedbacks.id"];
          form_id?: parameters["rowFilter.feedbacks.form_id"];
          type?: parameters["rowFilter.feedbacks.type"];
          feedback?: parameters["rowFilter.feedbacks.feedback"];
          name?: parameters["rowFilter.feedbacks.name"];
          url?: parameters["rowFilter.feedbacks.url"];
          is_public?: parameters["rowFilter.feedbacks.is_public"];
          created_at?: parameters["rowFilter.feedbacks.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.feedbacks.id"];
          form_id?: parameters["rowFilter.feedbacks.form_id"];
          type?: parameters["rowFilter.feedbacks.type"];
          feedback?: parameters["rowFilter.feedbacks.feedback"];
          name?: parameters["rowFilter.feedbacks.name"];
          url?: parameters["rowFilter.feedbacks.url"];
          is_public?: parameters["rowFilter.feedbacks.is_public"];
          created_at?: parameters["rowFilter.feedbacks.created_at"];
        };
        body: {
          /** feedbacks */
          feedbacks?: definitions["feedbacks"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/forms": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.forms.id"];
          slug?: parameters["rowFilter.forms.slug"];
          title?: parameters["rowFilter.forms.title"];
          description?: parameters["rowFilter.forms.description"];
          exposure?: parameters["rowFilter.forms.exposure"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["forms"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** forms */
          forms?: definitions["forms"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.forms.id"];
          slug?: parameters["rowFilter.forms.slug"];
          title?: parameters["rowFilter.forms.title"];
          description?: parameters["rowFilter.forms.description"];
          exposure?: parameters["rowFilter.forms.exposure"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.forms.id"];
          slug?: parameters["rowFilter.forms.slug"];
          title?: parameters["rowFilter.forms.title"];
          description?: parameters["rowFilter.forms.description"];
          exposure?: parameters["rowFilter.forms.exposure"];
        };
        body: {
          /** forms */
          forms?: definitions["forms"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  feedbacks: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `forms.id`.<fk table='forms' column='id'/>
     */
    form_id: string;
    /** Format: text */
    type?: string;
    /** Format: text */
    feedback?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    url?: string;
    /** Format: boolean */
    is_public?: boolean;
    /**
     * Format: timestamp with time zone
     * @default CURRENT_TIMESTAMP
     */
    created_at?: string;
  };
  forms: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: text */
    slug?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    exposure?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description feedbacks */
  "body.feedbacks": definitions["feedbacks"];
  /** Format: uuid */
  "rowFilter.feedbacks.id": string;
  /** Format: uuid */
  "rowFilter.feedbacks.form_id": string;
  /** Format: text */
  "rowFilter.feedbacks.type": string;
  /** Format: text */
  "rowFilter.feedbacks.feedback": string;
  /** Format: text */
  "rowFilter.feedbacks.name": string;
  /** Format: text */
  "rowFilter.feedbacks.url": string;
  /** Format: boolean */
  "rowFilter.feedbacks.is_public": string;
  /** Format: timestamp with time zone */
  "rowFilter.feedbacks.created_at": string;
  /** @description forms */
  "body.forms": definitions["forms"];
  /** Format: uuid */
  "rowFilter.forms.id": string;
  /** Format: text */
  "rowFilter.forms.slug": string;
  /** Format: text */
  "rowFilter.forms.title": string;
  /** Format: text */
  "rowFilter.forms.description": string;
  /** Format: text */
  "rowFilter.forms.exposure": string;
}

export interface operations {}

export interface external {}
